#:schema node_modules/wrangler/config-schema.json
name = "nicomt-dev"
compatibility_date = "2024-11-06"
assets = { directory = "./src/.vitepress/dist", not_found_handling = "404-page" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true